# fly.toml app configuration file generated for eaxi-books-fastify-misty-forest-9043 on 2025-08-01T19:43:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eaxi-books-fastify'
primary_region = 'jnb'

[build]

[http_service]
internal_port = 4500
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[metrics]
port = 9001
path = "/metrics"
