name: Deploy to GitHub Actions
on:
  push:
    branches:
      - main
env:
  FLY_API_KEY: ${{ secrets.FLY_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-action/setup-flyctl@master
      - run: flyctl deploy --app eaxi-books-fastify --remote-only
